CREATE TABLE IF NOT EXISTS Users (
    "userID" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "username" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "createdAtUTC" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAtUTC" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)