CREATE TABLE IF NOT EXISTS Reviews (
    "ID" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "movieID" UUID REFERENCES Movies("ID"),
    "rating" NUMERIC(2, 1) NOT NULL,
    "reviewText" TEXT,
    "createdAtUTC" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAtUTC" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);